wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1675367259.649881
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.13.9
      8:
      - 5
activation:
  desc: null
  value: sigmoid
bins_weighting:
  desc: null
  value: -1
bins_window:
  desc: null
  value: 3
checkpoint:
  desc: null
  value: null
cmap:
  desc: null
  value: ../data/emb/cmap_d_emb.h5
cmap_lang:
  desc: null
  value: ../data/emb/cmap_d_lang_emb.h5
conv_channels:
  desc: null
  value: '45'
conv_kernels:
  desc: null
  value: '5'
cross_block:
  desc: null
  value: 1
device:
  desc: null
  value: 0
input_dim:
  desc: null
  value: 6165
iter_dir:
  desc: null
  value: ../outputs/iter_50-bb-debug
lrate:
  desc: null
  value: 0.0001
model_type:
  desc: null
  value: -1
no_bins:
  desc: null
  value: 25
no_epoch:
  desc: null
  value: 50
no_heads:
  desc: null
  value: 5
output_prefix:
  desc: null
  value: ../outputs/iter_50-bb-debug/op_
proj_dim:
  desc: null
  value: 100
test:
  desc: null
  value: ../data/pairs/human_cm_dtest.tsv
test_image:
  desc: null
  value: 50
train:
  desc: null
  value: ../data/pairs/human_cm_dtrain.tsv
train_image:
  desc: null
  value: 50
